### ISSUE TITLE
Duplicate </td> and double public_html_merged folder

### ISSUE THREAD

**Issue by e2jk** [flightaware/dump1090#120]
Isn't there an issue with the current state of the `dev` branch?
While wanting to create a PR because of a duplicate `</td>` in `public_html/index.html` (which had been introduced in commit c2e1c1f6d59bec4108f58ec7cd2acd648694e2a7, particularly [this line](https://github.com/flightaware/dump1090/commit/c2e1c1f6d59bec4108f58ec7cd2acd648694e2a7?branch=c2e1c1f6d59bec4108f58ec7cd2acd648694e2a7&diff=unified#r48234629)) I noticed that there are now 2 folders `public_html` and `public_html_merged`. Is that on purpose, or the issue of a merge command ?

This is the line I wanted to fix, but with that `_merge` folder I'm not sure my PR wouldn't just cause more trouble.

https://github.com/flightaware/dump1090/blob/fe91fbc3a43dae9534769a2ae3b811c6037c76b7/public_html_merged/index.html#L206

**Comment by eric1tran** [comment]
Thanks, I've removed the extra </td> tag. 

The public_html_merged is intentional. This map contains all the new features and merges the 1090/978 aircraft together (previously we had separate dump1090-fa and skyaware978 maps at separate URLs). We plan to remove these in a future release as we move to one unified map.
