### ISSUE TITLE
Different CFLAGS for `cpu_features`

### ISSUE THREAD

**Issue by Lalufu** [flightaware/dump1090#130]
The `cpu_features` directory uses different CFLAGS/LDFLAGS than the main codebase (coming from `Makefile.cpufeatures`). What's the reason for this?
My main curiosity is because injecting different CFLAGS into the build process (as RPM building on RH systems does, to enable some safety features) applies to the main process, but not `cpu_features`.

**Comment by mutability** [comment]
`Makefile.cpufeatures` is basically there to avoid having to run a cmake build of cpu_features and then try to work out where it put everything. The cflags are different because cpu_features is a third-party library with its own compile requirements that don't necessarily line up with the main dump1090 cflags.

The eventual solution (probably) to move everything to cmake, but that is a larger project than I wanted to take on right now. Then you can do whatever you need to do for cmake globally.

For now, if you need to inject additional flags, you'll need to inject them into `CPUFEATURES_CFLAGS` too
