### ISSUE TITLE
UI showing _ infront of identities

### ISSUE THREAD

**Issue by diezel99** [flightaware/dump1090#85]
![Screen Shot 2020-10-02 at 4 27 00 PM](https://user-images.githubusercontent.com/33643213/94977125-3c832800-04cc-11eb-9a21-e9d52e30f086.png)

**Comment by mutability** [comment]
These are aircraft which are not transmitting a callsign; the registration with a leading `_` is shown instead.

**Comment by diezel99** [comment]
For the life of me, I didn't see that stated anywhere.

**Comment by mutability** [comment]
Yeah I don't think it is documented (and could be clearer)

**Comment by mutability** [comment]
@eric1tran can we do something clearer here e.g. use parentheses or make it italic or something like that?

**Comment by ericflightaware** [comment]
This is the same behavior as tar1090 and parallels the leading ~ formatting model for anonymous codes. A little in-line help/docs would go a long way here and could be used in a lot places.

**Comment by eric1tran** [comment]
I'd like to find a good place for SkyAware usage documentation. I started this as a placeholder https://github.com/flightaware/dump1090/tree/master/public_html but www.flightaware.com or integrating it into SkyAware itself would be more ideal. 

We can do it for the next release as we add more features/changes.

**Comment by mutability** [comment]
> parallels the leading ~ formatting model for anonymous codes

The leading `~` for non-ICAO addresses is an internal representation thing; it gets trimmed off by skyview and italics are used instead (at least in the table rows - the same really needs to be done in the aircraft detail pane too). We should do something similar for replacing ident with reg, a leading `_` is unclear because it looks like data from the aircraft itself and not a difference in data type.
